## Config file

# General
period: 1 #second



# Input
spark-master: spark://xx:4000
history-server: 142.150.208.177:18080

# Metrics
app:
- x

job:
- x

stage:
- x

task:
- x


# Output
redis: 10.2.3.4:5002
