## Config file

# General
period: 5 #second

# Input
spark-master: 142.150.208.147:4040
history-server: 142.150.208.147:18080

# Server: running/history
mode: history

# Parser type: app/job/stage/task
type: app

# Output
redis: 142.150.208.147:6379
